services: 
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/usr/src
      - /usr/src/node_modules
    ports:
      - "5173:5173"
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/www
    ports:
      - "5000:5000"
    environment:
      - DEV=true
    #env_file:
    #  - ./backend/.backend.env
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"